# Generated by Django 2.1.2 on 2018-10-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_userapplied'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapplied',
            name='amount_charge',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
