# Generated by Django 2.1.2 on 2018-10-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_userapplied_amount_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
