# Generated by Django 2.1.2 on 2018-10-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastjobs',
            name='profile',
        ),
    ]
