# Generated by Django 2.1.2 on 2018-10-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20181018_1421'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobManager',
        ),
        migrations.RemoveField(
            model_name='job',
            name='user',
        ),
        migrations.AlterField(
            model_name='job',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
    ]
