# Generated by Django 2.1.2 on 2018-10-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20181018_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='userapplied',
            name='user_applied',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
