# Generated by Django 2.1.2 on 2018-10-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20181022_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplied',
            name='amount_charge',
            field=models.CharField(max_length=200),
        ),
    ]
