# Generated by Django 2.1.2 on 2018-10-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20181022_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapplied',
            name='amount_charge',
        ),
        migrations.AddField(
            model_name='userapplied',
            name='amount_charged',
            field=models.IntegerField(default=0),
        ),
    ]
