# Generated by Django 2.1.2 on 2018-10-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20181023_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
